# Generated by Django 5.0.14 on 2026-02-03 19:39

import core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
from django.db import migrations, models


def cancel_overlapping_appointments(apps, schema_editor):
    """Cancel duplicate/overlapping appointments so the exclusion constraint can be applied."""
    Appointment = apps.get_model("core", "Appointment")

    # Find overlapping pairs: for each appointment, if another exists with same tenant,
    # overlapping range, and not CANCELLED/EXPIRED, cancel the one with higher id
    to_cancel = set()
    for apt in Appointment.objects.exclude(status__in=["CANCELLED", "EXPIRED"]).order_by("id"):
        if apt.id in to_cancel:
            continue
        overlaps = Appointment.objects.exclude(status__in=["CANCELLED", "EXPIRED"]).filter(
            tenant_id=apt.tenant_id,
            scheduled_at__lt=apt.end_time,
            end_time__gt=apt.scheduled_at,
        ).exclude(id=apt.id)
        for other in overlaps:
            to_cancel.add(other.id)
    if to_cancel:
        Appointment.objects.filter(id__in=to_cancel).update(status="CANCELLED")


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_appointment_model'),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.RunPython(cancel_overlapping_appointments, reverse_noop),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PRE_BOOKED', 'Pré-agendado'), ('CONFIRMED', 'Confirmado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Concluído'), ('NO_SHOW', 'Não compareceu')], default='PRE_BOOKED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['CANCELLED', 'EXPIRED']), _negated=True), expressions=[('tenant', '='), (core.models.TsTzRange('scheduled_at', 'end_time', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='no_overlap'),
        ),
    ]
