# Generated by Django 5.0.14 on 2026-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_exclusion_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
