# Generated by Django 5.0.14 on 2026-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_refund_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSED', 'Processado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20),
        ),
    ]
